# Generated by Django 5.0 on 2023-12-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemetadata',
            name='file',
            field=models.FileField(upload_to='assets.files'),
        ),
    ]
