# Generated by Django 5.0 on 2023-12-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_filemetadata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemetadata',
            name='file',
            field=models.FileField(upload_to='assets/files'),
        ),
    ]
