# Generated by Django 5.0 on 2023-12-18 02:17

import core.upload.user_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_filemetadata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemetadata',
            name='file',
            field=models.FileField(upload_to=core.upload.user_utils.user_directory_path),
        ),
    ]
